flowchart TB
 subgraph API["Controller Layer"]
        WC["WasteCategoryController"]
        DG["DisposalGuidelineController"]
        RT["RecyclingTipController"]
  end
 subgraph Services["Service Layer"]
        WS["WasteCategoryService"]
        DS["DisposalGuidelineService"]
        RS["RecyclingTipService"]
  end
 subgraph Repositories["Repository Layer"]
        WR["WasteCategoryRepository"]
        DR["DisposalGuidelineRepository"]
        RR["RecyclingTipRepository"]
  end
 subgraph LAYERS[" "]
        API
        Services
        Repositories
  end
    UI["API Clients"] L_UI_WC_0@<--> WC & DG & RT
    WC L_WC_WS_0@<--> WS
    DG <--> DS
    RT L_RT_RS_0@<--> RS
    WS L_WS_WR_0@<--> WR
    DS <--> DR
    RS L_RS_RR_0@<--> RR
    WR L_WR_DB_0@<--> DB[("Waste Management DB")]
    DR <--> DB
    RR L_RR_DB_0@<--> DB

    UI@{ shape: rounded}
     WC:::Pine
     DG:::Pine
     RT:::Pine
     WS:::Sky
     DS:::Sky
     RS:::Sky
     WR:::Peach
     DR:::Peach
     RR:::Peach
    classDef Sky stroke-width:1px, stroke-dasharray:none, stroke:#374D7C, fill:#E2EBFF, color:#374D7C
    classDef Pine stroke-width:1px, stroke-dasharray:none, stroke:#254336, fill:#27654A, color:#FFFFFF
    classDef Peach stroke-width:1px, stroke-dasharray:none, stroke:#FBB35A, fill:#FFEFDB, color:#8F632D
    style API fill:#C8E6C9,stroke:#333,stroke-width:1px
    style Services fill:#BBDEFB,stroke:#333,stroke-width:1px
    style Repositories fill:#FFF9C4,stroke:#333,stroke-width:1px,color:#000000
    style LAYERS fill:transparent
    linkStyle 0 stroke:#FFFFFF,fill:none
    linkStyle 1 stroke:#FFFFFF,fill:none
    linkStyle 2 stroke:#FFFFFF,fill:none
    linkStyle 3 stroke:#FFFFFF,fill:none
    linkStyle 4 stroke:#FFFFFF,fill:none
    linkStyle 5 stroke:#FFFFFF,fill:none
    linkStyle 6 stroke:#FFFFFF,fill:none
    linkStyle 7 stroke:#FFFFFF,fill:none
    linkStyle 8 stroke:#FFFFFF,fill:none
    linkStyle 9 stroke:#FFFFFF,fill:none
    linkStyle 10 stroke:#FFFFFF,fill:none
    linkStyle 11 stroke:#FFFFFF,fill:none

    L_UI_WC_0@{ animation: slow } 
    L_UI_RT_0@{ animation: slow } 
    L_WC_WS_0@{ animation: slow } 
    L_RT_RS_0@{ animation: slow } 
    L_WS_WR_0@{ animation: slow } 
    L_RS_RR_0@{ animation: slow } 
    L_WR_DB_0@{ animation: slow } 
    L_RR_DB_0@{ animation: slow } 

